import Head from 'next/head';
import { useContext, useEffect, useState } from 'react';
import { zksyncContext } from '../utils/context';
import { useRouter } from 'next/router';

export default function Home() {

  const { accountAddress, getAccountsInfo, connectionReq } = useContext(zksyncContext);

  const router = useRouter();

  const connectMetamask = async () => {
    await connectionReq();
    await getAccountsInfo();
  }

  useEffect(() => {
    getAccountsInfo();
  }, [])

  return (
    <>
      <Head>
        <title>Decentralised Messaging App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <>
          <div className='bg-green-200 w-[100vw] h-[100vh] flex flex-row'>
            <div className='bg-blue-400 w-[40vw] my-[5vh] rounded-l-3xl ml-[8vw]'>
              <p className='font-semibold text-3xl pt-[20vh] px-[5vw]'> Devil Entering <br /> <br /> Decentralised  Messaging world</p>
            </div>

            <div className='w-[40vw] my-[5vh] bg-white rounded-r-3xl'>
              <div className='border border-slate-300 rounded-[2vw] h-[62vh] mt-[15vh] mx-[5vw]'>
                <p className='pt-[20vh] pl-[5vw] font-bold text-2xl'>Welcome To Your Freedom World</p>
                <br />
                <br />
                <hr />
                <p className='pt-[4.5vh] pl-[10vw] font-semibold text-xl'>Please Login to Dapp</p>
                {accountAddress == null ?
                  <button className='mt-[8vh] rounded-lg w-[14vw] min-w-[14vw] ml-[8.5vw] bg-gradient-to-r from-[#A6C1EE] text-lg font-semibold h-[5vh] to-[#FBC2EB]' onClick={connectMetamask}>Connect To Metamask</button>
                  :
                  <button className='mt-[8vh] rounded-lg w-[14vw] min-w-[14vw] ml-[8.5vw] bg-gradient-to-r from-[#A6C1EE] text-lg font-semibold h-[5vh] to-[#FBC2EB]' onClick={() => router.push("/messaging")}>Enter Into the Application</button>
                }
              </div>
            </div>
          </div>
        </>
      </main>
    </>
  )
}
