import Head from 'next/head';
import { useContext, useEffect, useState } from 'react';
import { zksyncContext } from '../utils/context';

const messaging = () => {

    const { firstName, accountAddress, getAccountsInfo, convertTimeStamp, zksyncProvider, signerInstance, contractInstance, connectionReq } = useContext(zksyncContext);
    const [allUsers, setAllUsers] = useState([])
    const [allMessage, setAllMessage] = useState([]);
    const [date, setDate] = useState<string | null>(null)

    const indexNo: number = 2;

    useEffect(() => {
        getAccountsInfo();
    }, [])

    const getAllUsers = async () => {
        console.log(await contractInstance.getAllUsers())
        setAllUsers(await contractInstance.getAllUsers())
    }


    const sendMessage = async () => {
        try {
            await contractInstance.sendMessage("Testing Time", "0x9c69b9dE3439b397B921038229E69c6C4d0b3803");
            alert("Message Sent")
        } catch (error) {
            console.log(error)
        }
    }

    const readMessage = async () => {
        console.log(await contractInstance.readMessage("0x9c69b9dE3439b397B921038229E69c6C4d0b3803"))
        setAllMessage(await contractInstance.readMessage("0x9c69b9dE3439b397B921038229E69c6C4d0b3803"))
        if (allMessage[4]) {
            setDate(await convertTimeStamp(allMessage[4].timestamp))
            console.log(await convertTimeStamp(allMessage[4].timestamp))
        }
    }


    return (
        <>
            <Head>
                <title>Decentralised Messaging App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <>
                    <div>Hello {firstName}, Your Present Account Address is {accountAddress}</div>
                    <button onClick={getAllUsers}>Get All The Users</button>
                    <div>
                        {allUsers[0]}
                        <br />
                        {allUsers[1]}
                    </div>
                    <div>
                        <button onClick={sendMessage}>Send Message</button>
                        <button onClick={readMessage}>Read Message</button>
                        {date != null ? <p>{date}</p> : ""}
                        {allMessage != null ?
                            <>{allMessage.map((data, index) =>
                                <div key={index}>
                                    <p>{data.msgData}</p>
                                </div>
                            )}
                            </>
                            :
                            <p></p>
                        }
                    </div>
                </>
            </main>
        </>
    )
}

export default messaging